### PR TITLE
Update fdk-aac to 2.0.0

### PR DESCRIPTION
**Pull request by Erick555**
Also bump vlc to 3.0.8

### CODE REVIEW

**Comment by Erick555** [comment]
Build fails with:
```
codec/fdkaac.c: In function ‘OpenEncoder’:
codec/fdkaac.c:291:34: error: ‘AACENC_InfoStruct’ {aka ‘struct <anonymous>’} has no member named ‘encoderDelay’; did you mean ‘nDelay’?
     p_sys->i_encoderdelay = info.encoderDelay;
                                  ^~~~~~~~~~~~
```

**Comment by Erick555** [comment]
It seems this needs ffmpeg fix https://github.com/mstorsjo/fdk-aac/issues/93

**Comment by Erick555** [comment]
That fix seems to be [already included in ffmpeg 4.1+](https://github.com/FFmpeg/FFmpeg/commit/141c960e21d2860e354f9b90df136184dd00a9a8). Both runtime and vlc app have newer ffmpeg than this so I don't know what's missing here.

**Comment by MatMaul** [comment]
VLC has its own independent plugin for fdkaac, so not related to ffmpeg.
You should be fine by backporting this patch from VLC master:
http://git.videolan.org/?p=vlc.git;a=commit;h=6ea9b13fe82fae2b25b7371c6c36d6296db28ccb

**Comment by Erick555** [comment]
@MatMaul ready for testing

**Comment by MatMaul** [comment]
Thanks !

**Pull request merged**
